---
name: "Silver Layer Processing"
description: "Data cleansing and standardization"
version: "1.0"

source_configurations:
  - name: "customer_data"
    input:
      path: "s3://bronze/customers/"
      format: "delta"
    output:
      path: "s3://silver/customers/"
      format: "delta"
      partition_by: ["country", "update_date"]
    transformations:
      - type: "standardize_names"
        columns: ["first_name", "last_name"]
        rules:
          - "trim_whitespace"
          - "proper_case"
          - "remove_special_chars"
      - type: "standardize_address"
        columns: ["address_line1", "address_line2", "city", "state", "zip"]
        rules:
          - "uppercase_state"
          - "standardize_zip"
          - "validate_city_state"
      - type: "validate_email"
        columns: ["email"]
        rules:
          - "format_check"
          - "domain_check"
      - type: "deduplicate"
        key_columns: ["customer_id"]
        order_by: "update_timestamp DESC"
    quality_checks:
      - type: "uniqueness"
        columns: ["customer_id"]
      - type: "validity"
        rules:
          - column: "email"
            pattern: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$"
          - column: "phone"
            pattern: "^\\+?[1-9]\\d{1,14}$"

  - name: "transaction_data"
    input:
      path: "s3://bronze/transactions/"
      format: "delta"
    output:
      path: "s3://silver/transactions/"
      format: "delta"
      partition_by: ["transaction_date", "transaction_type"]
    transformations:
      - type: "standardize_currency"
        columns: ["amount", "currency"]
        target_currency: "USD"
        exchange_rate_source: "s3://reference-data/forex/"
      - type: "categorize_transactions"
        columns: ["description", "merchant_name"]
        category_mapping: "s3://reference-data/transaction_categories.json"
      - type: "enrich_location"
        columns: ["merchant_location"]
        reference_data: "s3://reference-data/locations/"
      - type: "validate_amounts"
        columns: ["amount", "fee", "total"]
        rules:
          - "non_negative"
          - "total_equals_amount_plus_fee"
    quality_checks:
      - type: "referential_integrity"
        columns: ["customer_id"]
        reference_table: "silver.customers"
        reference_columns: ["customer_id"]
      - type: "value_distribution"
        column: "transaction_type"
        expected_values: ["DEBIT", "CREDIT", "TRANSFER", "PAYMENT"]

  - name: "product_data"
    input:
      path: "s3://bronze/products/"
      format: "delta"
    output:
      path: "s3://silver/products/"
      format: "delta"
      partition_by: ["category", "active_status"]
    transformations:
      - type: "standardize_categories"
        columns: ["category", "subcategory"]
        mapping: "s3://reference-data/product_categories.json"
      - type: "price_normalization"
        columns: ["base_price", "discounted_price"]
        rules:
          - "round_to_2_decimals"
          - "validate_discount_rules"
      - type: "product_status"
        columns: ["status", "inventory_count"]
        rules:
          - "set_active_status"
          - "validate_inventory_threshold"
    quality_checks:
      - type: "price_validation"
        rules:
          - "base_price_greater_than_zero"
          - "discount_less_than_base_price"
      - type: "category_validation"
        rules:
          - "valid_category_hierarchy"
          - "no_orphan_subcategories"

processing_defaults:
  string_standardization:
    case: "proper"
    trim: true
    remove_special_chars: true
  numeric_standardization:
    decimal_places: 2
    format: "##,###.##"
  date_standardization:
    format: "yyyy-MM-dd"
    timezone: "UTC"

error_handling:
  max_retries: 3
  retry_interval: 300
  error_threshold: 0.01
  quarantine_path: "s3://quarantine/silver/{dataset_name}/"
  error_reporting:
    format: "json"
    location: "s3://logs/silver_processing/"

monitoring:
  metrics:
    - name: "records_processed"
      type: "counter"
      labels: ["dataset_name", "status"]
    - name: "processing_time"
      type: "histogram"
      labels: ["dataset_name", "transformation_type"]
    - name: "data_quality_score"
      type: "gauge"
      labels: ["dataset_name", "quality_dimension"]
  alerts:
    - name: "quality_threshold_breach"
      condition: "data_quality_score < 0.95"
      channels: ["slack", "email"]
    - name: "processing_delay"
      condition: "processing_time > 3600"
      channels: ["slack", "pagerduty"]
