apiVersion: v1
kind: ConfigMap
metadata:
  name: simulation-config
data:
  MINIO_ENDPOINT: minio:9000
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
  MINIO_SECURE: "false"
  API_URL: http://api-service:8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation
  labels:
    app: simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation
  template:
    metadata:
      labels:
        app: simulation
    spec:
      containers:
        - name: simulation
          image: cloud-agnostic-pipeline/simulation:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: simulation-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - "import sys; sys.exit(0)"
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - python
                - -c
                - "import sys; sys.exit(0)"
            initialDelaySeconds: 30
            periodSeconds: 30
