apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: data-pipeline
data:
  PYTHON_ENV: "production"
  SPARK_MASTER_URL: "spark://spark-master:7077"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  POSTGRES_HOST: "postgres"
  POSTGRES_DB: "pipeline_db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
  namespace: data-pipeline
data:
  spark-defaults.conf: |
    spark.master=k8s://https://kubernetes.default.svc
    spark.kubernetes.namespace=data-pipeline
    spark.kubernetes.container.image=pipeline-spark:latest
    spark.kubernetes.authenticate.driver.serviceAccountName=spark
    spark.executor.instances=2
    spark.executor.memory=2g
    spark.executor.cores=2
