apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-api
  namespace: data-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipeline-api
  template:
    metadata:
      labels:
        app: pipeline-api
    spec:
      serviceAccountName: pipeline-sa
      containers:
      - name: api
        image: pipeline-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: pipeline-config
        - secretRef:
            name: pipeline-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-master
  namespace: data-pipeline
spec:
  serviceName: spark-master
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:3.3.0
        ports:
        - containerPort: 7077
        - containerPort: 8080
        env:
        - name: SPARK_MODE
          value: master
        volumeMounts:
        - name: spark-config
          mountPath: /opt/bitnami/spark/conf
      volumes:
      - name: spark-config
        configMap:
          name: spark-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: data-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:3.3.0
        env:
        - name: SPARK_MODE
          value: worker
        - name: SPARK_MASTER_URL
          value: spark://spark-master:7077
        - name: SPARK_WORKER_MEMORY
          value: "2G"
        - name: SPARK_WORKER_CORES
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-api
  namespace: data-pipeline
spec:
  selector:
    app: pipeline-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: data-pipeline
spec:
  selector:
    app: spark-master
  ports:
  - name: master
    port: 7077
    targetPort: 7077
  - name: ui
    port: 8080
    targetPort: 8080
  type: ClusterIP
