apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secrets
  namespace: data-pipeline
type: Opaque
data:
  POSTGRES_USER: cGlwZWxpbmVfdXNlcg==  # pipeline_user
  POSTGRES_PASSWORD: cGlwZWxpbmVfcGFzc3dvcmQ=  # pipeline_password
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
  namespace: data-pipeline
type: Opaque
data:
  KAFKA_SASL_USERNAME: a2Fma2FfdXNlcg==  # kafka_user
  KAFKA_SASL_PASSWORD: a2Fma2FfcGFzc3dvcmQ=  # kafka_password
